package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"
	"strconv"

	"github.com/pganguli/hnews/graph/model"
	"github.com/pganguli/hnews/internal/auth"
	"github.com/pganguli/hnews/internal/links"
	"github.com/pganguli/hnews/internal/users"
	"github.com/pganguli/hnews/pkg/jwt"
)

// CreateLink is the resolver for the createLink field.
func (r *mutationResolver) CreateLink(ctx context.Context, input model.NewLink) (*model.Link, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return &model.Link{}, fmt.Errorf("access denied")
	}

	grahpqlUser := &model.User{
		ID:       strconv.Itoa(user.ID),
		Username: user.Username,
	}

	var link links.Link

	link.Title = input.Title
	link.Address = input.Address
	link.User = user

	linkID, err := link.Save()
	if err != nil {
		return &model.Link{}, err
	}

	return &model.Link{ID: strconv.Itoa(linkID), Title: link.Title, Address: link.Address, User: grahpqlUser}, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (string, error) {
	var user users.User

	user.Username = input.Username
	user.Password = input.Password

	err := user.Create()
	if err != nil {
		return "", err
	}

	token, err := jwt.GenerateToken(user.Username)
	if err != nil {
		return "", err
	}

	return token, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.Login) (string, error) {
	var user users.User

	user.Username = input.Username
	user.Password = input.Password

	match, err := user.Authenticate()
	if (!match) || (err != nil) {
		return "", &users.WrongUsernameOrPasswordError{}
	}

	token, err := jwt.GenerateToken(user.Username)

	if err != nil {
		return "", err
	}

	return token, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input model.RefreshTokenInput) (string, error) {
	username, err := jwt.ParseToken(input.Token)
	if err != nil {
		return "", fmt.Errorf("access denied")
	}

	token, err := jwt.GenerateToken(username)
	if err != nil {
		return "", err
	}

	return token, nil
}

// Links is the resolver for the links field.
func (r *queryResolver) Links(ctx context.Context) ([]*model.Link, error) {
	var resLinks []*model.Link

	dbLinks := links.GetAll()
	for _, link := range dbLinks {
		grahpqlUser := &model.User{
			ID:       strconv.Itoa(link.User.ID),
			Username: link.User.Username,
		}

		resLinks = append(resLinks, &model.Link{ID: strconv.Itoa(link.ID), Title: link.Title, Address: link.Address, User: grahpqlUser})
	}

	return resLinks, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
